//! Pre-rasterized bitmap font from "Noto Sans Mono", an open font from Google. \
//! * Downloaded from: <https://fonts.google.com/noto/specimen/Noto+Sans+Mono>
//! * License: SIL Open Font License (OFL) <https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL>
//!
//! # TL;DR
//! * ✅ most important symbols, numbers, and letters as pre-rasterized bitmap
//! * ✅ Noto Sans Mono font as base
//! * ✅ different sizes and font weights (light, normal, bold)
//! * ✅ nice anti-aliasing/smoothing and better looking than legacy bitmap fonts
//!
//! If all Cargo features are available, this bitmap fonts supports `light`, `regular`,
//! and `bold`, but no `italic` style, because Noto Sans Mono doesn't have a italic
//! TTF file. The rasterization was done with the awesome [fontdue-Crate](https://crates.io/crates/fontdue).
//!
//! It is highly recommended to only include the font style and font size that you need,
//! otherwise this will bloat your executable by a few megabytes.
//!
//! The bitmap font includes the following unicode range:
//! - BASIC LATIN,
//! - LATIN 1 Supplement
//! - LATIN EXTENDED-A
//!
//! This means unicode symbols from `0 .. 0x17f`, hence letters and
//! and symbols from a QWERTZ/QWERTY keyboard plus symbols such as
//! Ö, Ä, and Ü. Control characters are not included.
#![no_std]

// !!! THIS FILE GETS GENERATED BY THE "./codegen"-PROJECT. !!!

mod light;
mod regular;
mod bold;


/// Supported font weights.
///
/// The available variants depend on the selected Cargo build features.
#[derive(Debug, Copy, Clone)]
#[repr(usize)]
pub enum FontWeight {
    #[cfg(feature = "light")]
    Light,
    #[cfg(feature = "regular")]
    Regular,
    #[cfg(feature = "bold")]
    Bold,

}

impl FontWeight {
    /// Returns the numeric value of the enum variant.
    pub const fn val(self) -> usize {
        self as _
    }
}

/// The height of the bitmap font. The font size will be a a few
/// percent less, because each bitmap letter contains vertical padding
/// for proper alignment of chars (i.e. ÄyA). The width of each bitmap
/// character will be also less than the height, because there is no
/// horizontal padding included.
///
/// The available variants depend on the selected Cargo build features.
#[derive(Debug, Clone, Copy)]
#[repr(usize)]
pub enum BitmapHeight {
    #[cfg(feature = "size_14")]
    Size14 = 14,
    #[cfg(feature = "size_16")]
    Size16 = 16,
    #[cfg(feature = "size_18")]
    Size18 = 18,
    #[cfg(feature = "size_20")]
    Size20 = 20,
    #[cfg(feature = "size_22")]
    Size22 = 22,
    #[cfg(feature = "size_24")]
    Size24 = 24,
    #[cfg(feature = "size_32")]
    Size32 = 32,
    #[cfg(feature = "size_64")]
    Size64 = 64,

}

impl BitmapHeight {
    /// Returns the numeric value of the variant.
    pub const fn val(self) -> usize {
        self as _
    }
}

/// Returns the bitmap for the given char, [`FontWeight`], and [`BitmapHeight`].
#[inline]
pub const fn get_bitmap(c: char, style: FontWeight, size: BitmapHeight) -> &'static [&'static [u8]] {
    match style {
        #[cfg(feature = "light")]
        FontWeight::Light => match size.val() {
            #[cfg(feature = "size_14")]
            14 => crate::light::size_14::get_char(c),
            #[cfg(feature = "size_16")]
            16 => crate::light::size_16::get_char(c),
            #[cfg(feature = "size_18")]
            18 => crate::light::size_18::get_char(c),
            #[cfg(feature = "size_20")]
            20 => crate::light::size_20::get_char(c),
            #[cfg(feature = "size_22")]
            22 => crate::light::size_22::get_char(c),
            #[cfg(feature = "size_24")]
            24 => crate::light::size_24::get_char(c),
            #[cfg(feature = "size_32")]
            32 => crate::light::size_32::get_char(c),
            #[cfg(feature = "size_64")]
            64 => crate::light::size_64::get_char(c),
            _ => panic!("unknown variant"),
        }
        #[cfg(feature = "regular")]
        FontWeight::Regular => match size.val() {
            #[cfg(feature = "size_14")]
            14 => crate::regular::size_14::get_char(c),
            #[cfg(feature = "size_16")]
            16 => crate::regular::size_16::get_char(c),
            #[cfg(feature = "size_18")]
            18 => crate::regular::size_18::get_char(c),
            #[cfg(feature = "size_20")]
            20 => crate::regular::size_20::get_char(c),
            #[cfg(feature = "size_22")]
            22 => crate::regular::size_22::get_char(c),
            #[cfg(feature = "size_24")]
            24 => crate::regular::size_24::get_char(c),
            #[cfg(feature = "size_32")]
            32 => crate::regular::size_32::get_char(c),
            #[cfg(feature = "size_64")]
            64 => crate::regular::size_64::get_char(c),
            _ => panic!("unknown variant"),
        }
        #[cfg(feature = "bold")]
        FontWeight::Bold => match size.val() {
            #[cfg(feature = "size_14")]
            14 => crate::bold::size_14::get_char(c),
            #[cfg(feature = "size_16")]
            16 => crate::bold::size_16::get_char(c),
            #[cfg(feature = "size_18")]
            18 => crate::bold::size_18::get_char(c),
            #[cfg(feature = "size_20")]
            20 => crate::bold::size_20::get_char(c),
            #[cfg(feature = "size_22")]
            22 => crate::bold::size_22::get_char(c),
            #[cfg(feature = "size_24")]
            24 => crate::bold::size_24::get_char(c),
            #[cfg(feature = "size_32")]
            32 => crate::bold::size_32::get_char(c),
            #[cfg(feature = "size_64")]
            64 => crate::bold::size_64::get_char(c),
            _ => panic!("unknown variant"),
        }

    }
}

/// Returns the bitmap width for the given [`FontWeight`] and [`BitmapHeight`].
/// The width is a few percent smaller than the bitmap height, but constant
/// for each character of the pre rasterized bitmap font.
#[inline]
pub const fn get_bitmap_width(style: FontWeight, size: BitmapHeight) -> usize {
    match style {
        #[cfg(feature = "light")]
        FontWeight::Light => match size.val() {
            #[cfg(feature = "size_14")]
            14 => crate::light::size_14::BITMAP_WIDTH,
            #[cfg(feature = "size_16")]
            16 => crate::light::size_16::BITMAP_WIDTH,
            #[cfg(feature = "size_18")]
            18 => crate::light::size_18::BITMAP_WIDTH,
            #[cfg(feature = "size_20")]
            20 => crate::light::size_20::BITMAP_WIDTH,
            #[cfg(feature = "size_22")]
            22 => crate::light::size_22::BITMAP_WIDTH,
            #[cfg(feature = "size_24")]
            24 => crate::light::size_24::BITMAP_WIDTH,
            #[cfg(feature = "size_32")]
            32 => crate::light::size_32::BITMAP_WIDTH,
            #[cfg(feature = "size_64")]
            64 => crate::light::size_64::BITMAP_WIDTH,
            _ => panic!("unknown variant"),
        }
        #[cfg(feature = "regular")]
        FontWeight::Regular => match size.val() {
            #[cfg(feature = "size_14")]
            14 => crate::regular::size_14::BITMAP_WIDTH,
            #[cfg(feature = "size_16")]
            16 => crate::regular::size_16::BITMAP_WIDTH,
            #[cfg(feature = "size_18")]
            18 => crate::regular::size_18::BITMAP_WIDTH,
            #[cfg(feature = "size_20")]
            20 => crate::regular::size_20::BITMAP_WIDTH,
            #[cfg(feature = "size_22")]
            22 => crate::regular::size_22::BITMAP_WIDTH,
            #[cfg(feature = "size_24")]
            24 => crate::regular::size_24::BITMAP_WIDTH,
            #[cfg(feature = "size_32")]
            32 => crate::regular::size_32::BITMAP_WIDTH,
            #[cfg(feature = "size_64")]
            64 => crate::regular::size_64::BITMAP_WIDTH,
            _ => panic!("unknown variant"),
        }
        #[cfg(feature = "bold")]
        FontWeight::Bold => match size.val() {
            #[cfg(feature = "size_14")]
            14 => crate::bold::size_14::BITMAP_WIDTH,
            #[cfg(feature = "size_16")]
            16 => crate::bold::size_16::BITMAP_WIDTH,
            #[cfg(feature = "size_18")]
            18 => crate::bold::size_18::BITMAP_WIDTH,
            #[cfg(feature = "size_20")]
            20 => crate::bold::size_20::BITMAP_WIDTH,
            #[cfg(feature = "size_22")]
            22 => crate::bold::size_22::BITMAP_WIDTH,
            #[cfg(feature = "size_24")]
            24 => crate::bold::size_24::BITMAP_WIDTH,
            #[cfg(feature = "size_32")]
            32 => crate::bold::size_32::BITMAP_WIDTH,
            #[cfg(feature = "size_64")]
            64 => crate::bold::size_64::BITMAP_WIDTH,
            _ => panic!("unknown variant"),
        }

    }
}

